[project]
name = "psx-portfolio-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastmcp>=3.4.2",
    "mcp[cli]>=1.28.0",
    "psxdata>=0.1.0a3",
    "pywin32>=312",
    "requests>=2.34.2",
]
